"""Subclass of MainFrameStart, which is generated by wxFormBuilder."""

import wx
import gui

# Implementing MainFrameStart
class MainFrameStart( gui.MainFrameStart ):
	def __init__( self, parent ):
		gui.MainFrameStart.__init__( self, parent )
	
	# Handlers for MainFrameStart events.
	def m_mniOpenClick( self, event ):
		# TODO: Implement m_mniOpenClick
		pass
	
	def m_mniSaveClick( self, event ):
		# TODO: Implement m_mniSaveClick
		pass
	
	def m_mniExitClick( self, event ):
		# TODO: Implement m_mniExitClick
		pass
	
	def m_mniAboutClick( self, event ):
		# TODO: Implement m_mniAboutClick
		pass
	
	
